<?php

// Auto generated by wpfluent Installer.

return array(
    'name'           => 'FluentAffiliate',
    'slug'           => 'fluent-affiliate',
    'domain_path'    => '/language',
    'text_domain'    => 'fluent-affiliate',
    'hook_prefix'    => 'fluent_affiliate/',
    'rest_namespace' => 'fluent-affiliate',
    'rest_version'   => 'v2',
    'env'            => 'dev',
    'version'        => '1.0.0',
);
